2025-05-04 19:22:47,940 ERROR: Exception on /admin/add-content/lesson [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\admin\routes.py", line 22, in decorated_function
    return f(*args, **kwargs)
  File "E:\HK4\PythonProject\app\admin\routes.py", line 179, in add_content
    form.level_id.choices = [(l.level_id, l.level_name) for l in Level.query.all()]
                              ^^^^^^^^^^
AttributeError: 'Level' object has no attribute 'level_id'
2025-05-04 19:30:30,749 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:35:34,594 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:41:27,020 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:46:37,570 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:51:35,671 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:53:54,703 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 19:56:10,318 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:07:16,767 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:15:49,677 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:15:58,719 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:19:22,457 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:22:05,078 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:24:04,636 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:28:41,394 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
2025-05-04 20:29:13,433 ERROR: Exception on /lesson/1 [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\main\routes.py", line 130, in lesson
    return render_template('tutorials/lesson.html',
                           title=lesson.title,
                           lesson=lesson,
                           user_progress=user_progress,
                           completed=completed)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 152, in render_template
    return _render(app, template, context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 133, in _render
    rv = template.render(context)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "E:\HK4\PythonProject\app\templates\tutorials\lesson.html", line 1, in top-level template code
    {% extends "../base.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../base.html
2025-05-04 20:29:16,527 ERROR: Exception on /tutorials/ [GET] [in E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\.venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "E:\HK4\PythonProject\app\tutorials\routes.py", line 45, in index
    "name": level.name,
            ^^^^^^^^^^
AttributeError: 'Level' object has no attribute 'name'
2025-05-04 20:31:50,997 INFO: SpeakEasy startup [in E:\HK4\PythonProject\app\__init__.py:104]
